
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  #  depends_on:
   #   - backend

  # backend:
   # build: ./backend
    #ports:
     # - "3000:3000"
    #environment:
      # Configura la conexión a MySQL usando el nombre del servicio "mysql"
     # - DB_HOST=mysql
      #- DB_USER=root
      #- DB_PASSWORD=12345
      #- DB_NAME=
    #depends_on:
     # - mysql 

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


